import '../../../../core/models/entity_meta.dart';
import '../../../../core/services/entity_service.dart';

const agencyBrandLinkEntityMeta = EntityMeta(
  entityName: "Agency Brand Link",
  entityNameLower: "agency brand link",
  entityNamePlural: "Agency Brand Links",
  entityNamePluralLower: "agency brand links",
);

class ModelAgencyBrandLinkFields {
  static const String table = 'agency_brand_links';
  static const String tableViewWithForeignKeyLabels = 'view_agency_brand_links';

  static const String linkId = 'link_id';
  static const String agencyId = 'agency_id';
  static const String brandId = 'brand_id';
  static const String visitOrder = 'visit_order';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';

  static const Map<String, String> labels = {
    linkId: 'Agency-Brand Link',
    agencyId: 'Agency',
    brandId: 'Brand',
    visitOrder: 'Visit Order',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
  };

  static String getLabel(String field) => labels[field] ?? field;
}

class ModelAgencyBrandLink {
  final String? linkId; // nullable, generated by DB
  final String? agencyId; // nullable FK
  final String? brandId; // nullable FK
  final int? visitOrder; // nullable
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default
  final Map<String, dynamic> _resolvedLabels;

  ModelAgencyBrandLink({
    this.linkId,
    this.agencyId,
    this.brandId,
    this.visitOrder,
    this.createdAt,
    this.updatedAt,
    Map<String, dynamic>? resolvedLabels,
  }) : _resolvedLabels = resolvedLabels ?? const {};

  Map<String, dynamic> get resolvedLabels => _resolvedLabels;

  factory ModelAgencyBrandLink.fromMap(Map<String, dynamic> map) {
    final labelEntries = <String, dynamic>{};
    for (final entry in map.entries) {
      if (entry.key.endsWith('_label')) {
        labelEntries[entry.key] = entry.value;
      }
    }

    return ModelAgencyBrandLink(
      linkId: map[ModelAgencyBrandLinkFields.linkId],
      agencyId: map[ModelAgencyBrandLinkFields.agencyId],
      brandId: map[ModelAgencyBrandLinkFields.brandId],
      visitOrder: map[ModelAgencyBrandLinkFields.visitOrder],
      createdAt: _parseDate(map[ModelAgencyBrandLinkFields.createdAt]),
      updatedAt: _parseDate(map[ModelAgencyBrandLinkFields.updatedAt]),
      resolvedLabels: labelEntries,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (linkId != null) ModelAgencyBrandLinkFields.linkId: linkId,
      if (agencyId != null) ModelAgencyBrandLinkFields.agencyId: agencyId,
      if (brandId != null) ModelAgencyBrandLinkFields.brandId: brandId,
      if (visitOrder != null) ModelAgencyBrandLinkFields.visitOrder: visitOrder,
      if (createdAt != null)
        ModelAgencyBrandLinkFields.createdAt: createdAt!.toIso8601String(),
      if (updatedAt != null)
        ModelAgencyBrandLinkFields.updatedAt: updatedAt!.toIso8601String(),
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'linkId': linkId,
      'agencyId': agencyId,
      'brandId': brandId,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'visitOrder': visitOrder,
    };
  }

  factory ModelAgencyBrandLink.fromJson(Map<String, dynamic> json) {
    return ModelAgencyBrandLink(
      linkId: json['linkId'] as String,
      agencyId: json['agencyId'] as String?,
      brandId: json['brandId'] as String?,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
      visitOrder: json['visitOrder'] as int?,
    );
  }

  static DateTime? _parseDate(dynamic value) {
    if (value == null) return null;
    if (value is DateTime) return value;
    return DateTime.tryParse(value.toString());
  }

  ModelAgencyBrandLink copyWith({
    String? linkId,
    String? agencyId,
    String? brandId,
    int? visitOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? resolvedLabels,
  }) {
    return ModelAgencyBrandLink(
      linkId: linkId ?? this.linkId,
      agencyId: agencyId ?? this.agencyId,
      brandId: brandId ?? this.brandId,
      visitOrder: visitOrder ?? this.visitOrder,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      resolvedLabels: resolvedLabels ?? _resolvedLabels,
    );
  }
}

class ModelAgencyBrandLinkMapper implements EntityMapper<ModelAgencyBrandLink> {
  @override
  ModelAgencyBrandLink fromMap(Map<String, dynamic> map) =>
      ModelAgencyBrandLink.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelAgencyBrandLink entity) => entity.toMap();
}
