import '../../../../core/models/entity_meta.dart';
import '../../../../core/services/entity_service.dart';

const agencyEntityMeta = EntityMeta(
  entityName: 'Agency',
  entityNamePlural: 'Agencies',
  entityNameLower: 'agency',
  entityNamePluralLower: 'agencies',
);

class ModelAgencyFields {
  static const String table = 'agencies';

  static const String agencyId = 'agency_id';
  static const String agencyName = 'agency_name';
  static const String agencyNote = 'agency_note';
  static const String isActive = 'is_active';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';
  static const String createdBy = 'created_by';
  static const String updatedBy = 'updated_by';
}

class ModelAgency {
  final String? agencyId; // nullable, generated by DB
  final String agencyName; // required
  final String? agencyNote; // nullable
  final bool isActive; // default true
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default
  final String? createdBy; // nullable
  final String? updatedBy; // nullable

  ModelAgency({
    this.agencyId,
    required this.agencyName,
    this.agencyNote,
    this.isActive = true,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
  });

  factory ModelAgency.fromMap(Map<String, dynamic> map) {
    return ModelAgency(
      agencyId: map[ModelAgencyFields.agencyId],
      agencyName: map[ModelAgencyFields.agencyName],
      agencyNote: map[ModelAgencyFields.agencyNote],
      isActive: map[ModelAgencyFields.isActive] ?? true,
      createdAt: map[ModelAgencyFields.createdAt] != null
          ? DateTime.tryParse(map[ModelAgencyFields.createdAt])
          : null,
      updatedAt: map[ModelAgencyFields.updatedAt] != null
          ? DateTime.tryParse(map[ModelAgencyFields.updatedAt])
          : null,
      createdBy: map[ModelAgencyFields.createdBy],
      updatedBy: map[ModelAgencyFields.updatedBy],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (agencyId != null) ModelAgencyFields.agencyId: agencyId,
      ModelAgencyFields.agencyName: agencyName,
      if (agencyNote != null) ModelAgencyFields.agencyNote: agencyNote,
      ModelAgencyFields.isActive: isActive,
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'agencyId': agencyId,
      'agencyName': agencyName,
      'agencyNote': agencyNote,
      'isActive': isActive,
    };
  }

  factory ModelAgency.fromJson(Map<String, dynamic> json) {
    return ModelAgency(
      agencyId: json['agencyId'] as String,
      agencyName: json['agencyName'] as String,
      agencyNote: json['agencyNote'] as String?,
      isActive: json['isActive'] as bool? ?? true,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
      createdBy: json['createdBy'] as String?,
      updatedBy: json['updatedBy'] as String?,
    );
  }
}

class ModelAgencyMapper implements EntityMapper<ModelAgency> {
  @override
  ModelAgency fromMap(Map<String, dynamic> map) => ModelAgency.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelAgency entity) => entity.toMap();
}
