import '../../../../core/services/entity_service.dart';

class ModelBrandFields {
  static const String table = 'brands';
  static const String tableViewWithForeignKeyLabels = 'view_brands';

  static const String brandId = 'brand_id';
  static const String brandName = 'brand_name';
  static const String brandsPrimaryAgency = 'brands_primary_agency';
  static const String brandNote = 'brand_note';
  static const String hiddenNote = 'hidden_note';
  static const String brandMobile1 = 'brand_mobile_1';
  static const String brandMobile2 = 'brand_mobile_2';
  static const String brandPersonName = 'brand_person_name';
  static const String isActive = 'is_active';
  static const String brandLocationUrl = 'brand_location_url';
  static const String brandLandmark = 'brand_landmark';
  static const String brandAddress = 'brand_address';
  static const String brandPhotoId = 'brand_photo_id';
  static const String brandPhotoUrl = 'brand_photo_url';
  static const String brandLat = 'brand_lat';
  static const String brandLong = 'brand_long';
  static const String androidAppId = 'android_app_id';
  static const String websiteUrl = 'website_url';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';
  static const String createdBy = 'created_by';
  static const String updatedBy = 'updated_by';
  static const String visitOrder = 'visit_order';

  static const Map<String, String> labels = {
    brandId: 'Brand',
    brandName: 'Brand Name',
    brandsPrimaryAgency: 'Primary Agency',
    brandNote: 'Brand Note',
    hiddenNote: 'Hidden Note',
    brandMobile1: 'Mobile 1',
    brandMobile2: 'Mobile 2',
    brandPersonName: 'Contact Person',
    isActive: 'Is Active',
    brandLocationUrl: 'Location URL',
    brandLandmark: 'Landmark',
    brandAddress: 'Address',
    brandPhotoId: 'Photo ID',
    brandPhotoUrl: 'Photo URL',
    brandLat: 'Latitude',
    brandLong: 'Longitude',
    androidAppId: 'Android App ID',
    websiteUrl: 'Website URL',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    createdBy: 'Created By',
    updatedBy: 'Updated By',
    visitOrder: 'Visit Order',
  };

  static String getLabel(String field) => labels[field] ?? field;
}

class ModelBrand {
  final String? brandId; // nullable, generated by DB
  final String brandName; // required
  final String? brandsPrimaryAgency; // nullable FK
  final String? brandNote;
  final String? hiddenNote;
  final String? brandMobile1;
  final String? brandMobile2;
  final String? brandPersonName;
  final bool isActive; // default true
  final String? brandLocationUrl;
  final String? brandLandmark;
  final String? brandAddress;
  final String? brandPhotoId;
  final String? brandPhotoUrl;
  final double? brandLat;
  final double? brandLong;
  final String? androidAppId;
  final String? websiteUrl;
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default
  final String? createdBy;
  final String? updatedBy;
  final int? visitOrder;
  final Map<String, dynamic> _resolvedLabels;

  ModelBrand({
    this.brandId,
    required this.brandName,
    this.brandsPrimaryAgency,
    this.brandNote,
    this.hiddenNote,
    this.brandMobile1,
    this.brandMobile2,
    this.brandPersonName,
    this.isActive = true,
    this.brandLocationUrl,
    this.brandLandmark,
    this.brandAddress,
    this.brandPhotoId,
    this.brandPhotoUrl,
    this.brandLat,
    this.brandLong,
    this.androidAppId,
    this.websiteUrl,
    this.createdAt,
    this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.visitOrder,
    Map<String, dynamic>? resolvedLabels,
  }) : _resolvedLabels = resolvedLabels ?? const {};

  Map<String, dynamic> get resolvedLabels => _resolvedLabels;

  factory ModelBrand.fromMap(Map<String, dynamic> map) {
    final labelEntries = <String, dynamic>{};
    for (final entry in map.entries) {
      if (entry.key.endsWith('_label')) {
        labelEntries[entry.key] = entry.value;
      }
    }

    return ModelBrand(
      brandId: map[ModelBrandFields.brandId],
      brandName: map[ModelBrandFields.brandName],
      brandsPrimaryAgency: map[ModelBrandFields.brandsPrimaryAgency],
      brandNote: map[ModelBrandFields.brandNote],
      hiddenNote: map[ModelBrandFields.hiddenNote],
      brandMobile1: map[ModelBrandFields.brandMobile1],
      brandMobile2: map[ModelBrandFields.brandMobile2],
      brandPersonName: map[ModelBrandFields.brandPersonName],
      isActive: map[ModelBrandFields.isActive] ?? true,
      brandLocationUrl: map[ModelBrandFields.brandLocationUrl],
      brandLandmark: map[ModelBrandFields.brandLandmark],
      brandAddress: map[ModelBrandFields.brandAddress],
      brandPhotoId: map[ModelBrandFields.brandPhotoId],
      brandPhotoUrl: map[ModelBrandFields.brandPhotoUrl],
      brandLat: map[ModelBrandFields.brandLat]?.toDouble(),
      brandLong: map[ModelBrandFields.brandLong]?.toDouble(),
      androidAppId: map[ModelBrandFields.androidAppId],
      websiteUrl: map[ModelBrandFields.websiteUrl],
      createdAt: map[ModelBrandFields.createdAt] != null
          ? DateTime.tryParse(map[ModelBrandFields.createdAt])
          : null,
      updatedAt: map[ModelBrandFields.updatedAt] != null
          ? DateTime.tryParse(map[ModelBrandFields.updatedAt])
          : null,
      createdBy: map[ModelBrandFields.createdBy],
      updatedBy: map[ModelBrandFields.updatedBy],
      visitOrder: map[ModelBrandFields.visitOrder] as int?,
      resolvedLabels: labelEntries,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (brandId != null) ModelBrandFields.brandId: brandId,
      ModelBrandFields.brandName: brandName,
      if (brandsPrimaryAgency != null)
        ModelBrandFields.brandsPrimaryAgency: brandsPrimaryAgency,
      if (brandNote != null) ModelBrandFields.brandNote: brandNote,
      if (hiddenNote != null) ModelBrandFields.hiddenNote: hiddenNote,
      if (brandMobile1 != null) ModelBrandFields.brandMobile1: brandMobile1,
      if (brandMobile2 != null) ModelBrandFields.brandMobile2: brandMobile2,
      if (brandPersonName != null)
        ModelBrandFields.brandPersonName: brandPersonName,
      ModelBrandFields.isActive: isActive,
      if (brandLocationUrl != null)
        ModelBrandFields.brandLocationUrl: brandLocationUrl,
      if (brandLandmark != null) ModelBrandFields.brandLandmark: brandLandmark,
      if (brandAddress != null) ModelBrandFields.brandAddress: brandAddress,
      if (brandPhotoId != null) ModelBrandFields.brandPhotoId: brandPhotoId,
      if (brandPhotoUrl != null) ModelBrandFields.brandPhotoUrl: brandPhotoUrl,
      if (brandLat != null) ModelBrandFields.brandLat: brandLat,
      if (brandLong != null) ModelBrandFields.brandLong: brandLong,
      if (androidAppId != null) ModelBrandFields.androidAppId: androidAppId,
      if (websiteUrl != null) ModelBrandFields.websiteUrl: websiteUrl,
      if (visitOrder != null) ModelBrandFields.visitOrder: visitOrder,
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'brandId': brandId,
      'brandName': brandName,
      'brandsPrimaryAgency': brandsPrimaryAgency,
      'brandNote': brandNote,
      'hiddenNote': hiddenNote,
      'brandMobile1': brandMobile1,
      'brandMobile2': brandMobile2,
      'brandPersonName': brandPersonName,
      'isActive': isActive,
      'brandLocationUrl': brandLocationUrl,
      'brandLandmark': brandLandmark,
      'brandAddress': brandAddress,
      'brandPhotoId': brandPhotoId,
      'brandPhotoUrl': brandPhotoUrl,
      'brandLat': brandLat,
      'brandLong': brandLong,
      'androidAppId': androidAppId,
      'websiteUrl': websiteUrl,
      'visitOrder': visitOrder,
    };
  }

  factory ModelBrand.fromJson(Map<String, dynamic> json) {
    return ModelBrand(
      brandId: json['brandId'] as String,
      brandName: json['brandName'] as String,
      brandsPrimaryAgency: json['brandsPrimaryAgency'] as String?,
      brandNote: json['brandNote'] as String?,
      hiddenNote: json['hiddenNote'] as String?,
      brandMobile1: json['brandMobile1'] as String?,
      brandMobile2: json['brandMobile2'] as String?,
      brandPersonName: json['brandPersonName'] as String?,
      isActive: json['isActive'] as bool? ?? true,
      brandLocationUrl: json['brandLocationUrl'] as String?,
      brandLandmark: json['brandLandmark'] as String?,
      brandAddress: json['brandAddress'] as String?,
      brandPhotoId: json['brandPhotoId'] as String?,
      brandPhotoUrl: json['brandPhotoUrl'] as String?,
      brandLat: (json['brandLat'] as num?)?.toDouble(),
      brandLong: (json['brandLong'] as num?)?.toDouble(),
      androidAppId: json['androidAppId'] as String?,
      websiteUrl: json['websiteUrl'] as String?,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
      visitOrder: json['visitOrder'] as int?,
    );
  }
}

class ModelBrandMapper implements EntityMapper<ModelBrand> {
  @override
  ModelBrand fromMap(Map<String, dynamic> map) => ModelBrand.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelBrand entity) => entity.toMap();
}
