import '../../../../core/models/entity_meta.dart';
import '../../../../core/services/entity_service.dart';

const rbacModuleEntityMeta = EntityMeta(
  entityName: "Route Brand Link",
  entityNameLower: "route brand link",
  entityNamePlural: "Route Brand Links",
  entityNamePluralLower: "route brand links",
);

class ModelRouteBrandLinkFields {
  static const String table = 'route_brand_links';
  static const String tableViewWithForeignKeyLabels = 'view_route_brand_links';

  static const String linkId = 'link_id';
  static const String routeId = 'route_id';
  static const String brandId = 'brand_id';
  static const String visitOrder = 'visit_order';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';

  static const Map<String, String> labels = {
    linkId: 'Route-Brand Link',
    routeId: 'Route',
    brandId: 'Brand',
    visitOrder: 'Visit Order',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
  };

  static String getLabel(String field) => labels[field] ?? field;
}

class ModelRouteBrandLink {
  final String? linkId; // nullable, generated by DB
  final String? routeId; // nullable FK
  final String? brandId; // nullable FK
  final int? visitOrder; // nullable
  final DateTime? createdAt; // nullable, DB default
  final DateTime? updatedAt; // nullable, DB default
  final Map<String, dynamic> _resolvedLabels;

  ModelRouteBrandLink({
    this.linkId,
    this.routeId,
    this.brandId,
    this.visitOrder,
    this.createdAt,
    this.updatedAt,
    Map<String, dynamic>? resolvedLabels,
  }) : _resolvedLabels = resolvedLabels ?? const {};

  Map<String, dynamic> get resolvedLabels => _resolvedLabels;

  factory ModelRouteBrandLink.fromMap(Map<String, dynamic> map) {
    final labelEntries = <String, dynamic>{};
    for (final entry in map.entries) {
      if (entry.key.endsWith('_label')) {
        labelEntries[entry.key] = entry.value;
      }
    }

    return ModelRouteBrandLink(
      linkId: map[ModelRouteBrandLinkFields.linkId],
      routeId: map[ModelRouteBrandLinkFields.routeId],
      brandId: map[ModelRouteBrandLinkFields.brandId],
      visitOrder: map[ModelRouteBrandLinkFields.visitOrder],
      createdAt: _parseDate(map[ModelRouteBrandLinkFields.createdAt]),
      updatedAt: _parseDate(map[ModelRouteBrandLinkFields.updatedAt]),
      resolvedLabels: labelEntries,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      if (linkId != null) ModelRouteBrandLinkFields.linkId: linkId,
      if (routeId != null) ModelRouteBrandLinkFields.routeId: routeId,
      if (brandId != null) ModelRouteBrandLinkFields.brandId: brandId,
      if (visitOrder != null) ModelRouteBrandLinkFields.visitOrder: visitOrder,
      if (createdAt != null)
        ModelRouteBrandLinkFields.createdAt: createdAt!.toIso8601String(),
      if (updatedAt != null)
        ModelRouteBrandLinkFields.updatedAt: updatedAt!.toIso8601String(),
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'linkId': linkId,
      'routeId': routeId,
      'brandId': brandId,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'visitOrder': visitOrder,
    };
  }

  factory ModelRouteBrandLink.fromJson(Map<String, dynamic> json) {
    return ModelRouteBrandLink(
      linkId: json['linkId'] as String,
      routeId: json['routeId'] as String?,
      brandId: json['brandId'] as String?,
      createdAt: DateTime.tryParse(json['createdAt'] ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(json['updatedAt'] ?? '') ?? DateTime.now(),
      visitOrder: json['visitOrder'] as int?,
    );
  }

  static DateTime? _parseDate(dynamic value) {
    if (value == null) return null;
    if (value is DateTime) return value;
    return DateTime.tryParse(value.toString());
  }

  ModelRouteBrandLink copyWith({
    String? linkId,
    String? routeId,
    String? brandId,
    int? visitOrder,
    DateTime? createdAt,
    DateTime? updatedAt,
    Map<String, dynamic>? resolvedLabels,
  }) {
    return ModelRouteBrandLink(
      linkId: linkId ?? this.linkId,
      routeId: routeId ?? this.routeId,
      brandId: brandId ?? this.brandId,
      visitOrder: visitOrder ?? this.visitOrder,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      resolvedLabels: resolvedLabels ?? _resolvedLabels,
    );
  }
}

class ModelRouteBrandLinkMapper implements EntityMapper<ModelRouteBrandLink> {
  @override
  ModelRouteBrandLink fromMap(Map<String, dynamic> map) =>
      ModelRouteBrandLink.fromMap(map);

  @override
  Map<String, dynamic> toMap(ModelRouteBrandLink entity) => entity.toMap();
}
